"""empty message

Revision ID: 94d9050d1103
Revises: 4df3a6504a16
Create Date: 2023-11-29 13:19:54.853671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d9050d1103'
down_revision = '4df3a6504a16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    with op.batch_alter_table('surf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surf', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('skis', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
